### ISSUE TITLE
Replace swagger-tools with @Axway/swagger-tools

### ISSUE THREAD

**Issue by hrgondaliya** [Axway/swagger-tools#8]
I want to replace swagger-tools with @Axway/swagger-tools in my app. There is a security concern on "swagger-tools" related to "validators". Now, they are not maintaining it anymore. 

I did check your package and it looks nice with fixed security issues. Do we have any documentation on it how I can use this?

I am getting an error on middleware initialization.

Error initializing middleware
TypeError: middleware.swaggerUi is not a function

Thanks in Advance.

**Comment by wickedest** [comment]
@hrgondaliya, sorry, I was unaware you posted this question. In the changelog, in version 0.11.0, we removed the bundled swagger-ui support, and browser support.
